---
title: Weather dashboard
hero_image: images/banner.png
description: 
version: 4
listed: true
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
- title: Explore weather data
- title: Create a weather dashboard
  completion:
  - engaged
- title: Create a function
  completion:
  - internal
